name: staticcheck

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "here we go"
    - uses: actions/checkout@v3
    
    - name: flujo_installcppcheck_and_doxygen
      run: |
       sudo apt-get update
       sudo apt-get install cppcheck
       sudo apt-get install doxygen
    
    - name: flujo_runcppcheck_path
      run: |
        cppcheck --enable=all SDcardBootloader --xml 2> SDcardBootloader/htmlREPORTcppcheck/cppcheck-result.xml
        
    - name: flujo_rundoxygen
      run: |
        cd documentation_doxygen
        doxygen config_doxygen.conf
        
    - name: flujo_htmlreport_download
      run: |
       cd ..
        wget https://github.com/danmar/cppcheck/tree/main/htmlreport
        cppcheck-htmlreport --source-dir=SDcardBootloader/. --title=htmlREPORTcppcheck --file=SDcardBootloader/htmlREPORTcppcheck/cppcheck-result.xml --report-dir=SDcardBootloader/htmlREPORTcppcheck
        
#    - name: flujo update changes
#      run: |
#         git config --global user.email ${{ secrets.mailsecreto }}
#         git config --global user.name ${{ secrets.usersecreto }}
#         git config --global credential.helper cache
#         git add .
#         git commit -m "report autogenerated $(date)"
#         git push
